https:
  port: "8082"
   
mysql:
  host: "1platform-mysql.demos.mulesoft.com" 
  port: "3306"
  schema: "1platform_orders"
  user: "orders"
  password: "WaXPdw9GBR4xfQrt"
  
api:
  autodiscovery: "15523420"

keystore:
  path: "keystore.jks"
  password: "Mule1379?"